#!/usr/bin/python3
import socket
import select
import sys
#Checking for sufficient arguments
if len(sys.argv)!=3:
	print("./chatclient ip:port nickname")
	sys.exit(1)

client_socket = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
client_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

cmd = sys.argv[1].split(':')
ip = str(cmd[0])
port = int(cmd[1])
nickname = str(sys.argv[2])

#Connecting to the socket
client_socket.connect((ip,port))
res1 = client_socket.recv(1024).decode("utf-8")
print(res1)

#Sending nickname
nick = 'NICK '+nickname
client_socket.sendall(nick.encode('utf-8'))
res2 = client_socket.recv(1024).decode("utf-8")
print(res2)
if res2 == 'ERROR malformed command':
	print(res2)
	sys.exit()


while True:
	try:
		#List of possible operations		
		sockets_list = [sys.stdin,client_socket]
		#Three descriptors as parameters on which the select function can block-read,write and exception.
		read_sockets,write_sockets,exception_sockets = select.select(sockets_list,[],[])

		for socket in read_sockets:
			# Server sending message
			if socket == client_socket:
				msg = socket.recv(2048).decode('utf-8')
				sys.stdout.write(msg)
			
			#User sending message	
			else:
				msg = sys.stdin.readline()
				if msg == '\n':
					continue;
				else:
					message = 'MSG '+msg
					client_socket.sendall(message.encode('utf-8'))

	except KeyboardInterrupt:
                    break

client_socket.close()
